repos:
  #-   repo: local
  #    hooks:
  #    - id: pytest-check
  #      name: pytest-check
  #      stages: [commit]
  #      types: [python]
  #      entry: pytest
  #      language: system
  #      pass_filenames: false
  #      always_run: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-yaml
    -   id: debug-statements
        exclude: tests/
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      files: \.(py)$
-   repo: local
    hooks:
     - id: TODO
       language: system
       name: TODO detection
       entry: bash -c "for ITEM in $(grep $@ -rl -e '# TODO');do  echo 'WARNING - TODO tags found! in '$ITEM; done || true"
       files: \.(py)$
       verbose: true
     - id: NO_COMMIT
       language: system
       name: no-commit detection
       exclude: '.pre-commit-config.yaml'
       entry: bash -c "for ITEM in $(grep $@ -rl -e '!nocommit');do  echo 'WARNING - !nocommit tags found! in '$ITEM && exit 1; done"
